default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: Test_school_development
test:
  <<: *default
  database: Test_school_test
staging:
  <<: *default
  database: Test_school_staging

production:
  <<: *default
  database: Test_school_production
